<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tresorerie.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Transactions" />
    <Reference Include="Tresorerie.Infrastructure">
      <HintPath>..\..\..\GRFWinform\Tresorerie.Infrastructure.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="Tresorerie.Ressources">
      <HintPath>..\..\..\GRFWinform\Tresorerie.Ressources.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>..\..\..\GRFWinform\Serilog.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>