USE GR_EMA_DISTRIBUTION;

PRINT 'Total rows in RT_HISTCOMPTA:';
SELECT COUNT(*) AS Total_HistCompta FROM RT_HISTCOMPTA;

PRINT 'Total matches:';
SELECT COUNT(*) AS Match_Count
FROM RT_HISTCOMPTA h
INNER JOIN [NEW_EMA DISTRIBUTION].dbo.F_ECRITUREC f ON h.HC_No = f.cbMarq;

PRINT 'Unmatched HC_No:';
SELECT TOP 100 h.HC_No, h.HC_Jour, h.HC_NumPiece, h.HC_Montant, h.HC_Sens
FROM RT_HISTCOMPTA h
LEFT JOIN [NEW_EMA DISTRIBUTION].dbo.F_ECRITUREC f ON h.HC_No = f.cbMarq
WHERE f.cbMarq IS NULL;
